chickenflask/notes/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask import current_app as app
from flask_login import current_user, login_required
from .models import db, NotesCategory, NotesSubcategory, NotesEntry
from .forms import NotesEntryForm, NotesDeleteForm, CategoryEntryForm, SubcategoryEntryForm, CatDeleteForm


# Blueprint Configuration
notes_bp = Blueprint(
    'notes_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@app.context_processor
def notes_sidebar_processor():
    if current_user.is_authenticated:
        d = {cat.name: {subcat.name: {entry.name: url_for('notes_bp.notes', cat=cat.name, subcat=subcat.name, entry=entry.name) for entry in subcat.entries} for subcat in cat.sub_categories}
             for cat in NotesCategory.query.order_by(NotesCategory.priority).all()}
    else:
        d = {}
    return {'dropdowns': d}


@notes_bp.route('/markdown', methods=['GET'])
@login_required
def markdown_view():
    entry = NotesEntry.query.filter_by(name='Markdown').first_or_404()
    subcat = NotesSubcategory.query.filter_by(name=entry.parent.name).first_or_404()
    cat = subcat.parent_name
    return redirect(url_for('notes_bp.notes', cat=cat, subcat=subcat.name, entry=entry.name))


@notes_bp.route('/<string:cat>/<string:subcat>/<string:entry>', methods=['GET'])
@login_required
def notes(cat, subcat, entry):
    e = NotesEntry.query.filter_by(name=entry).first_or_404()
    return render_template('notes/notes.jinja2', category=cat, subcategory=subcat, entry=e, title=e.name)


@notes_bp.route('/manage', methods=['GET'])
@login_required
def manage_notes():
    return render_template('notes/notesmanager.jinja2', categories=NotesCategory.query.all(), subcategories=NotesSubcategory.query.all(), entries=NotesEntry.query.all())


@notes_bp.route('/add', methods=['GET'])
@login_required
def add_notes():
    entry_form = NotesEntryForm()
    delete_form = NotesDeleteForm()
    category_form = CategoryEntryForm()
    subcategory_form = SubcategoryEntryForm()
    cat_delete_form = CatDeleteForm()
    return render_template('notes/notesadder.jinja2', entry_form=entry_form, delete_form=delete_form,
                           category_form=category_form, subcategory_form=subcategory_form, cat_delete_form=cat_delete_form)


@notes_bp.route('/manage/addentry', methods=['GET', 'POST'])
@login_required
def manage_notes_add_entry():
    form = NotesEntryForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            new_entry = NotesEntry(name=form.name.data, drive_url=form.drive_url.data, parent_name=form.subcategory.data)
            db.session.add(new_entry)
            db.session.commit()
            flash(f'Success! Added {new_entry.name} in {form.category.data} - {form.subcategory.data}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/addcategory', methods=['GET', 'POST'])
@login_required
def manage_notes_add_category():
    form = CategoryEntryForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            new_entry = NotesCategory(name=form.name.data)
            db.session.add(new_entry)
            db.session.commit()
            flash(f'Success! Created new category: {new_entry.name}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/addsubcategory', methods=['GET', 'POST'])
@login_required
def manage_notes_add_subcategory():
    form = SubcategoryEntryForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            new_entry = NotesSubcategory(name=form.name.data, parent_name=form.category.data)
            db.session.add(new_entry)
            db.session.commit()
            flash(f'Success! Created new subcategory: {new_entry.name} ({new_entry.parent_name})')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/deleteentry', methods=['GET', 'POST'])
@login_required
def manage_notes_delete_entry():
    form = NotesDeleteForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            entry = NotesEntry.query.filter_by(name=form.name.data).first()
            db.session.delete(entry)
            db.session.commit()
            flash(f'Success! Deleted {entry.name}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/deletecat', methods=['GET', 'POST'])
@login_required
def manage_notes_delete_cat():
    form = CatDeleteForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            if form.model_type.data == 'category':
                c = NotesCategory.query.filter_by(name=form.name.data).first()
                assert len(c.sub_categories) == 0
            else:
                c = NotesSubcategory.query.filter_by(name=form.name.data).first()
                assert len(c.entries) == 0
            db.session.delete(c)
            db.session.commit()
            flash(f'Success! Deleted {c.name}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/update/<string:id>', methods=['GET'])
@login_required
def manage_notes_update(id):
    entry = NotesEntry.query.filter_by(id=id).first()
    entry.get_content_from_drive()
    db.session.commit()
    flash(f'Entry updated')

    return redirect(request.referrer)


@notes_bp.route('/edit/<string:id>')
@login_required
def notes_edit(id):
    entry = NotesEntry.query.filter_by(id=id).first()
    return render_template('notes/noteseditor.jinja2', entry=entry)


@notes_bp.route('/editsave/<string:id>', methods=['POST'])
@login_required
def notes_edit_save(id):
    try:
        editor_content = request.form.to_dict()['text_data']
        entry = NotesEntry.query.filter_by(id=id).first()
        entry.save_and_sync_content(editor_content)
        db.session.commit()
        flash(f'Success! Saved and synced content for {entry.name}')
    except Exception as err:
        flash(f'Save and sync error, check for mismatch! {err}')
        return ''
    return url_for('notes_bp.notes', cat=entry.parent.parent_name, subcat=entry.parent_name, entry=entry.name)
    # return redirect(url_for('notes_bp.notes', cat=entry.parent.parent_name, subcat=entry.parent_name, entry=entry.name))


@notes_bp.route('/mdtrial', methods=['GET'])
def mdtrial():
    editor_content = 'Title\n=====\n\nSubtitle\n--------\n\nText  \n**Bold Text**\n\nSubtitle 2\n----\n\nBye!'
    return render_template('notes/mdtrial.jinja2', editor_content=editor_content)


@notes_bp.route('/mdtrialrf', methods=['POST'])
def mdtrialrf():
    editor_content = request.form.to_dict()['text_data']
    return render_template('notes/mdtrialrf.jinja2', editor_content=editor_content)

chickenflask/notes/templates/notes/mdtrial.jinja2
{% extends 'basetemplate.jinja2' %}


{% block styles %}
    {{ super() }}
    <link href="https://cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet">
{% endblock %}


{% block contentheadblock %}
    Markdown Trial
{% endblock %}


{% block contentbodyblock %}

    <div id="toolbar">
        <h5 style="margin: 2px">Markdown Editor</h5>
        {# <button class="ql-bold">Bold</button>
        <button class="ql-italic">Italic</button> #}
    </div>

    <p id="default-text" style="display: none">{{ editor_content }}</p>
    <div id="editor" style="height: 30vh; font-family: 'Courier New'; font-size: 14px">
        <p>Text</p>
    </div>


    <div>
        <button class="preview-button" id="preview-button">Preview</button>
    </div>

    <div id="rendered-input">
        {{ editor_content|markdown }}
    </div>
{% endblock %}


{% block contentfootblock %}

{% endblock %}


{% block scripts %}
    {{ super() }}
    {# Insert additionnal scripts here #}
    <script src="https://cdn.quilljs.com/1.0.0/quill.js"></script>

    <script>
        var editor = new Quill('#editor', {
            modules: { toolbar: '#toolbar'},
            theme: 'snow'
        });
    </script>

    <script>
        {#
        let previewBtn = document.getElementById('preview-button');
        previewBtn.addEventListener("click", function() {
            //let content = document.getElementById('editor')
            console.log(JSON.stringify(editor.getContents()));

            let t = editor.getContents()['ops'];
            let text = '';
            var textPart;
            var inp = document.querySelector('input[name=about]');
            inp.value = editor.getContents();
            console.log(t);

            for (textPart of t) {
                text += textPart['insert'];

            }
            $.post(url_for('home_bp.stuff'), editor.getContents());
            //document.getElementById('rendered-input').insertAdjacentText("afterbegin", text);
        }); #}
    </script>
    <script>
    $(document).ready(function (){

        // Adjust css of new editor div and set default text (setting via html doesn't render newlines)
        $('.ql-editor').css('padding', '2px 2px');
        //$('.ql-toolbar').css('display', 'none');
        editor.setText($('#default-text').text());

        // Sent post to adjust display on button click
        $('.preview-button').on('click', function (){

           let t = editor.getContents()['ops'];
           let text = '';
           let textPart;
           for (textPart of t) {
                text += textPart['insert'];
           }

           let req = $.ajax({
               url:  "{{ url_for('notes_bp.mdtrialrf') }}",
               type: 'POST',
               data: {text_data: text}
           });

           req.done(function(data){
               $('#rendered-input').html(data);
           });

        });
    });

    </script>
{% endblock %}

chickenflask/notes/templates/notes/mdtrialrf.jinja2
{{ editor_content|markdown }}

chickenflask/notes/templates/notes/notes.jinja2
{% extends 'basetemplate.jinja2' %}

{% block styles %}
    {{ super() }}
    {% assets "notes_less" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
{% endblock %}

{% block contentheadblock %}
    {{ category }} > {{ subcategory }} > {{ entry.name }} <a href="{{ url_for('notes_bp.notes_edit', id=entry.id) }}" style="float: right; color:#ae1b1b">Edit</a>
{% endblock %}


{% block contentbodyblock %}

    <div class="note-content">
        {% if entry.content == '' %}
            This entry has not content
        {% elif entry.content_type == 'markdown' %}
            {{ entry.content|markdown }}
        {% else %}
            {{ entry.content }}
        {% endif %}
    </div>

    <br>

{% endblock %}


{% block contentfootblock %}
    <p style="text-align: center">
        <a class="" style="color: black" href="{{ entry.drive_url }}" target="_blank">View in Drive</a> | Last Updated: {{ entry.get_last_updated() }} | <a class="" style="color: black" href="{{ url_for('notes_bp.manage_notes_update', id=entry.id) }}">Force update</a>
    </p>
    {{ super() }}
{% endblock %}

chickenflask/notes/templates/notes/notesadder.jinja2
{% extends 'basetemplate.jinja2' %}

{% block styles %}
    {{ super() }}
    {% assets "notes_less" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
{% endblock %}

{% block contentheadblock %}
    Manage Notes
{% endblock %}


{% block contentbodyblock %}

    <div class="forms-div">
    <div class="form-wrapper">

        <h3>Add Notes Entry</h3>

        <form method="POST" action="{{ url_for('notes_bp.manage_notes_add_entry') }}">
            {{ entry_form.csrf_token }}

            <fieldset class="text-field">
                {{ entry_form.name.label }}
                {{ entry_form.name }}
            </fieldset>

            <fieldset class="text-field">
                {{ entry_form.drive_url.label }}
                {{ entry_form.drive_url }}
                {% if entry_form.drive_url.errors %}
                <ul class="errors">
                    {% for error in entry_form.drive_url.errors %}
                    <li>{{ error }}</li>{% endfor %}
                </ul>
                {% endif %}
            </fieldset>

            <fieldset class="select-field">
                {{ entry_form.category.label }}
                {{ entry_form.category }}
            </fieldset>

            <fieldset class="select-field">
                {{ entry_form.subcategory.label }}
                {{ entry_form.subcategory }}
            </fieldset>

            <div class="submit-button">
                {{ entry_form.submit }}
            </div>

        </form>
    </div>

    <div class="form-wrapper">

        <h3>Add Notes Category</h3>

        <form method="POST" action="{{ url_for('notes_bp.manage_notes_add_category') }}">
            {{ category_form.csrf_token }}

            <fieldset class="text-field">
                {{ category_form.name.label }}
                {{ category_form.name }}
            </fieldset>

            <div class="submit-button">
                {{ category_form.submit }}
            </div>

        </form>
    </div>

    <div class="form-wrapper">

        <h3>Add Notes Subategory</h3>

        <form method="POST" action="{{ url_for('notes_bp.manage_notes_add_subcategory') }}">
            {{ subcategory_form.csrf_token }}

            <fieldset class="text-field">
                {{ subcategory_form.name.label }}
                {{ subcategory_form.name }}
            </fieldset>

            <fieldset class="select-field">
                {{ subcategory_form.category.label }}
                {{ subcategory_form.category }}
            </fieldset>

            <div class="submit-button">
                {{ subcategory_form.submit }}
            </div>

        </form>
    </div>

    <div class="form-wrapper">

        <h3>Delete Notes Entry</h3>

        <form method="POST" action="{{ url_for('notes_bp.manage_notes_delete_entry') }}">
            {{ delete_form.csrf_token }}

            <fieldset class="text-field">
                {{ delete_form.name.label }}
                {{ delete_form.name }}
            </fieldset>

            <div class="submit-button">
                {{ delete_form.submit }}
            </div>

        </form>
    </div>

    <div class="form-wrapper">

        <h3>Delete Notes Category or Subcategory</h3>

        <form method="POST" action="{{ url_for('notes_bp.manage_notes_delete_cat') }}">
            {{ cat_delete_form.csrf_token }}

            <fieldset class="text-field">
                {{ cat_delete_form.name.label }}
                {{ cat_delete_form.name }}
            </fieldset>

            <fieldset class="select-field">
                {{ cat_delete_form.model_type.label }}
                {{ cat_delete_form.model_type }}
            </fieldset>

            <div class="submit-button">
                {{ cat_delete_form.submit }}
            </div>

        </form>

    <div style="padding-top: 30px">
        <h3>Notes Tree</h3>
        <ul class="notes-tree">
            {% for cat in dropdowns %}
                <li>
                    <h4>{{ cat }}</h4>
                    <ul>
                        {% for subcat in dropdowns[cat] %}
                            <li>
                                <h5>{{ subcat }}</h5>
                                <ul>
                                    {% for entry in dropdowns[cat][subcat] %}
                                        <li>{{ entry }}</li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}


{% block contentfootblock %}
    {{ super() }}
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script>

        let category_select = document.getElementById('category');
        let subcategory_select = document.getElementById('subcategory');
        let cats = {{ dropdowns }};
        console.log(category_select)
        console.log('asda')

        category_select.addEventListener('change', function () {
            let options_html = '';
            for (let subcat of Object.keys(cats[category_select.value])) {
                options_html += '<option value="' + subcat + '">' + subcat + '</option>';
            }
            subcategory_select.innerHTML = options_html;
        });

        category_select.dispatchEvent(new Event('change'));

    </script>

{% endblock %}

chickenflask/notes/templates/notes/noteseditor.jinja2
{% extends 'basetemplate.jinja2' %}


{% block styles %}
    {{ super() }}
    <link href="https://cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet">
    {% assets "notes_less" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
{% endblock %}


{% block contentheadblock %}
    Note Editor - {{ entry.name }}
{% endblock %}


{% block contentbodyblock %}

    <div id="toolbar">
        <h5 style="margin: 2px">Markdown Editor</h5>
        {# <button class="ql-bold">Bold</button>
        <button class="ql-italic">Italic</button> #}
    </div>

    <p id="default-text" style="display: none">{{ entry.content }}</p>
    <div id="editor" style="height: 60vh;font-family: 'Courier New'; font-size: 14px">
        <p>Text</p>
    </div>

    <div>
        <button class="save-button" id="save-button">Save</button>
    </div>

{% endblock %}


{% block contentfootblock %}

{% endblock %}


{% block scripts %}
    {{ super() }}
    {# Insert additionnal scripts here #}
    <script src="https://cdn.quilljs.com/1.0.0/quill.js"></script>

    <script>
        var editor = new Quill('#editor', {
            modules: { toolbar: '#toolbar'},
            theme: 'snow',
            scrollingContainer: '#scrolling-container',
        });
    </script>

    <script>
        {#
        let previewBtn = document.getElementById('preview-button');
        previewBtn.addEventListener("click", function() {
            //let content = document.getElementById('editor')
            console.log(JSON.stringify(editor.getContents()));

            let t = editor.getContents()['ops'];
            let text = '';
            var textPart;
            var inp = document.querySelector('input[name=about]');
            inp.value = editor.getContents();
            console.log(t);

            for (textPart of t) {
                text += textPart['insert'];

            }
            $.post(url_for('home_bp.stuff'), editor.getContents());
            //document.getElementById('rendered-input').insertAdjacentText("afterbegin", text);
        }); #}
    </script>
    <script>
    $(document).ready(function (){

        // Adjust css of new editor div and set default text (setting via html doesn't render newlines)
        $('.ql-editor').css('padding', '2px 2px');
        //$('.ql-toolbar').css('display', 'none');
        editor.setText($('#default-text').text());

        // Sent post to adjust display on button click
        // TODO save and save+exit. Same class to assing, then use ids and if to redirect or not
        $('.save-button').on('click', function (){

           let t = editor.getContents()['ops'];
           let text = '';
           let textPart;
           for (textPart of t) {
                text += textPart['insert'];
           }

           //$.post("{{ url_for('notes_bp.notes_edit_save', id=entry.id) }}", {text_data: text});

           let req = $.ajax({
               url:  "{{ url_for('notes_bp.notes_edit_save', id=entry.id) }}",
               type: 'POST',
               data: {text_data: text},
               success: function(redir) {
                   window.location.href = redir;
               }
           });

           //req.done(function(data){
             //  $('#rendered-input').html(data);
           //});

        });
    });

    </script>
{% endblock %}

chickenflask/notes/templates/notes/notesmanager.jinja2
{% extends 'basetemplate.jinja2' %}

{% block styles %}
    {{ super() }}
    {% assets "notes_less" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
{% endblock %}

{% block contentheadblock %}
    Manage Notes Dynamic test
{% endblock %}


{% block contentbodyblock %}
    {% from 'notes/notesmanagermacros.jinja2' import catmacro, entrymacro %}
    <div class="notesmanager-categories">
    {% for cat in categories %}
        <div class="notesmanager-category">{{ catmacro(cat) }}</div>
        <div class="notesmanager-subcategories">
        {% for subcat in cat.sub_categories %}
            <div class="notesmanager-subcategory">{{ catmacro(subcat, 'Subcategory') }}</div>
            <div class="notesmanager-entries">
            {% for entry in subcat.entries %}
                <div class="notesmanager-entry">
                    {{ entrymacro(entry) }}
                </div>
            {% endfor %}
            </div>
        {% endfor %}
        </div>
    {% endfor %}
    </div>
{% endblock %}


{% block contentfootblock %}
    {{ super() }}
{% endblock %}


{% block scripts %}
    {{ super() }}

{% endblock %}

chickenflask/notes/templates/notes/notesmanagermacros.jinja2
{% macro catmacro(cat, type='Category') %}
    <div class="catmacro-content">
        <h4>{{ type }} {{ cat.id }}</h4>
        {{ cat.name }} - {{ cat.priority }} - Save button - Del button
    </div>
{% endmacro %}

{% macro entrymacro(entry) %}
    <div class="entrymacro-content">
        <h4>Entry {{ entry.id }}</h4>
         {{ entry.name }} - {{ entry.drive_url }} - Save button - Delete Button
    </div>
{% endmacro %}