chickenflask/home/auth.py
"""Routes for user authentication."""
from flask import Blueprint, redirect, render_template, flash, request, session, url_for
from flask_login import login_required, logout_user, current_user, login_user
from .forms import LoginForm
from .models import db, User
from chickenflask import login_manager
#from .forms import LoginForm, SignupForm
#from .models import User, db


# Blueprint Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.

    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """

    # Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('home_bp.home'))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(name=form.name.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('home_bp.home'))
        # flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template(
        'home/login.jinja2',
        form=form,
        title='Log in',
        template='login-page',
        body="Log in with your User account."
    )


@auth_bp.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('home_bp.home'))


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    # flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

chickenflask/notes/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask import current_app as app
from flask_login import current_user, login_required
from .models import db, NotesCategory, NotesSubcategory, NotesEntry
from .forms import NotesEntryForm, NotesDeleteForm, CategoryEntryForm, SubcategoryEntryForm, CatDeleteForm


# Blueprint Configuration
notes_bp = Blueprint(
    'notes_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@app.context_processor
def notes_sidebar_processor():
    if current_user.is_authenticated:
        d = {cat.name: {subcat.name: {entry.name: url_for('notes_bp.notes', cat=cat.name, subcat=subcat.name, entry=entry.name) for entry in subcat.entries} for subcat in cat.sub_categories}
             for cat in NotesCategory.query.order_by(NotesCategory.priority).all()}
    else:
        d = {}
    return {'dropdowns': d}


@notes_bp.route('/markdown', methods=['GET'])
@login_required
def markdown_view():
    entry = NotesEntry.query.filter_by(name='Markdown').first_or_404()
    subcat = NotesSubcategory.query.filter_by(name=entry.parent.name).first_or_404()
    cat = subcat.parent_name
    return redirect(url_for('notes_bp.notes', cat=cat, subcat=subcat.name, entry=entry.name))


@notes_bp.route('/<string:cat>/<string:subcat>/<string:entry>', methods=['GET'])
@login_required
def notes(cat, subcat, entry):
    e = NotesEntry.query.filter_by(name=entry).first_or_404()
    return render_template('notes/notes.jinja2', category=cat, subcategory=subcat, entry=e, title=e.name)


@notes_bp.route('/manage', methods=['GET'])
@login_required
def manage_notes():
    return render_template('notes/notesmanager.jinja2', categories=NotesCategory.query.all(), subcategories=NotesSubcategory.query.all(), entries=NotesEntry.query.all())


@notes_bp.route('/add', methods=['GET'])
@login_required
def add_notes():
    entry_form = NotesEntryForm()
    delete_form = NotesDeleteForm()
    category_form = CategoryEntryForm()
    subcategory_form = SubcategoryEntryForm()
    cat_delete_form = CatDeleteForm()
    return render_template('notes/notesadder.jinja2', entry_form=entry_form, delete_form=delete_form,
                           category_form=category_form, subcategory_form=subcategory_form, cat_delete_form=cat_delete_form)


@notes_bp.route('/manage/addentry', methods=['GET', 'POST'])
@login_required
def manage_notes_add_entry():
    form = NotesEntryForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            new_entry = NotesEntry(name=form.name.data, drive_url=form.drive_url.data, parent_name=form.subcategory.data)
            db.session.add(new_entry)
            db.session.commit()
            flash(f'Success! Added {new_entry.name} in {form.category.data} - {form.subcategory.data}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/addcategory', methods=['GET', 'POST'])
@login_required
def manage_notes_add_category():
    form = CategoryEntryForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            new_entry = NotesCategory(name=form.name.data)
            db.session.add(new_entry)
            db.session.commit()
            flash(f'Success! Created new category: {new_entry.name}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/addsubcategory', methods=['GET', 'POST'])
@login_required
def manage_notes_add_subcategory():
    form = SubcategoryEntryForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            new_entry = NotesSubcategory(name=form.name.data, parent_name=form.category.data)
            db.session.add(new_entry)
            db.session.commit()
            flash(f'Success! Created new subcategory: {new_entry.name} ({new_entry.parent_name})')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/deleteentry', methods=['GET', 'POST'])
@login_required
def manage_notes_delete_entry():
    form = NotesDeleteForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            entry = NotesEntry.query.filter_by(name=form.name.data).first()
            db.session.delete(entry)
            db.session.commit()
            flash(f'Success! Deleted {entry.name}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/deletecat', methods=['GET', 'POST'])
@login_required
def manage_notes_delete_cat():
    form = CatDeleteForm()
    if request.method == 'POST' and form.is_submitted():
        try:
            if form.model_type.data == 'category':
                c = NotesCategory.query.filter_by(name=form.name.data).first()
                assert len(c.sub_categories) == 0
            else:
                c = NotesSubcategory.query.filter_by(name=form.name.data).first()
                assert len(c.entries) == 0
            db.session.delete(c)
            db.session.commit()
            flash(f'Success! Deleted {c.name}')
        except Exception as err:
            flash(f'Error! {err}')
    return redirect(url_for('notes_bp.add_notes'))


@notes_bp.route('/manage/update/<string:id>', methods=['GET'])
@login_required
def manage_notes_update(id):
    entry = NotesEntry.query.filter_by(id=id).first()
    entry.get_content_from_drive()
    db.session.commit()
    flash(f'Entry updated')

    return redirect(request.referrer)


@notes_bp.route('/edit/<string:id>')
@login_required
def notes_edit(id):
    entry = NotesEntry.query.filter_by(id=id).first()
    return render_template('notes/noteseditor.jinja2', entry=entry)


@notes_bp.route('/editsave/<string:id>', methods=['POST'])
@login_required
def notes_edit_save(id):
    try:
        editor_content = request.form.to_dict()['text_data']
        entry = NotesEntry.query.filter_by(id=id).first()
        entry.save_and_sync_content(editor_content)
        db.session.commit()
        flash(f'Success! Saved and synced content for {entry.name}')
    except Exception as err:
        flash(f'Save and sync error, check for mismatch! {err}')
        return ''
    return url_for('notes_bp.notes', cat=entry.parent.parent_name, subcat=entry.parent_name, entry=entry.name)
    # return redirect(url_for('notes_bp.notes', cat=entry.parent.parent_name, subcat=entry.parent_name, entry=entry.name))


@notes_bp.route('/mdtrial', methods=['GET'])
def mdtrial():
    editor_content = 'Title\n=====\n\nSubtitle\n--------\n\nText  \n**Bold Text**\n\nSubtitle 2\n----\n\nBye!'
    return render_template('notes/mdtrial.jinja2', editor_content=editor_content)


@notes_bp.route('/mdtrialrf', methods=['POST'])
def mdtrialrf():
    editor_content = request.form.to_dict()['text_data']
    return render_template('notes/mdtrialrf.jinja2', editor_content=editor_content)

chickenflask/templates/basetemplate.jinja2
{% extends 'layout.jinja2' %}

{% block headblock %}
    {{ super() }}
    {# Insert additionnal meta or header tags here #}
{% endblock %}

{% block styles %}
    {{ super() }}
    {# Insert additionnal styles here #}
{% endblock %}


{% block bodyblock %}

    {% block sideblock %}
        {% include 'sidenav.jinja2' %}
    {% endblock %}

    <div class="content">

        <div class="header">
            <p>
                <b>Chickenswell</b><i><span style="color: #ae1b1b; font-size: 14px">.com</span></i>
            <span style="text-align: right; float: right">
                {% if current_user.is_authenticated %}
                    Logged in as {{ current_user.name }} | <a href="{{ url_for('auth_bp.logout') }}" style="color: black">Logout</a>
                {% else %}
                    <a href="{{ url_for('auth_bp.login') }}" style="color: black">Login</a>
                {% endif %}
            </span>
            </p>
        </div>

        <div class="contenthead">
            <h3>
            {% block contentheadblock %}
                Chickenswell
            {% endblock %}
            </h3>
        </div>

        <hr style="width:96%">


        <div class="contentbody">

            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="alert">
		                <input type="checkbox" id="alert-close"/>
                        <label class="alert-close" title="close" for="alert-close">
                            <i class="fa fa-window-close"></i>
                        </label>
		                <p class="alert-inner">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
		                </p>
	                </div>
                {% endif %}
            {% endwith %}

            {% block contentbodyblock %}
                <p><h3>mainblock</h3></p>
                <p>contentbody pladeholder</p>
                <p>More text asdasd ger gerg er blablabla</p>
            {% endblock %}
        </div>

        <hr style="width:96%">

        <div class="contentfoot">
            {% block contentfootblock %}
                <p style="text-align: center"><a href="{{ url_for('home_bp.home') }}">Home</a> | ©Polycarpelegrand | <a href="https://github.com/PolycarpeLeGrand?tab=repositories" target="_blank">GitHub</a></p>
            {% endblock %}
        </div>

    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    {# Insert additionnal scripts here #}
{% endblock %}

chickenflask/templates/head.jinja2
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta charset="UTF-8">
<meta name="description" content="Add user authentication to your Flask app."/>
<meta name="HandheldFriendly" content="True"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
<meta name="theme-color" content="#5eb9d7"/>

<title>{{ title|default("Chickenswell", true) }}</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="shortcut icon" href="{{ url_for('static', filename='img/chickenswell_logo_200x200.png') }}" type="image/x-icon"/>
<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

chickenflask/templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    {% block headblock %}
        {% include 'head.jinja2' %}
    {% endblock %}

    {% block styles %}
        <link
            href="{{ url_for('static', filename='dist/css/style.css') }}"
            rel="stylesheet"
            type="text/css"
        />
    {% endblock %}

</head>

<body>
    {% block bodyblock %}
    {% endblock %}
</body>

{% block scripts %}
{% endblock %}

chickenflask/templates/mainlayout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta charset="UTF-8">
    <meta name="description" content="Add user authentication to your Flask app."/>
    <meta name="HandheldFriendly" content="True"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
    <meta name="theme-color" content="#5eb9d7"/>

    <title>{{ title }}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/chickenswell_logo_200x200.png') }}" type="image/x-icon"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet" type="text/css">
    {% endblock %}
    {% block pagestyles %}{% endblock %}
</head>

<body class="layout">

<div class="sidebar">
    <div class="homelogo">
        <a href="#">
            <img src="{{ url_for('static', filename='img/chickenswell_logo_200x200.png') }}" class="logo" alt="Chickenswell logo :("/>
        </a>
    </div>
    <a href="#news">News</a>
    <a href="#contact">Contact</a>
    <a href="#about">About</a>
</div>


<div class="content">
    {% block content %}{% endblock %}
</div>


{% block additionalscripts %}{% endblock %}
</body>

</html>

chickenflask/templates/sidenav.jinja2
<div class="sidebar">
    <div class="homelogo">
        <a href="/">
            <img src="{{ url_for('static', filename='img/chickenswell_logo_200x200.png') }}" class="logo" alt="Chickenswell logo :("/>
        </a>
    </div>

    <div class="sidenav">
        <a href="/">Home</a>
        <a href="{{ url_for('notes_bp.mdtrial') }}">Markdown Trial</a>
        <a href="{{ url_for('notes_bp.markdown_view') }}">Markdown Notes</a>
        <hr>
        {% if current_user.is_authenticated %}
            {% for dropdown in dropdowns %}
                <button class="dropdown-btn" id="{{ dropdown }}">
                    {{ dropdown }}
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    {% for sub_cat in dropdowns[dropdown] %}
                        {# <a href={{ sub_cat }}>{{ sub_cat }}</a> #}
                        <button class="sub-dropdown-btn" id="{{ sub_cat }}">
                            <i class="fa fa-caret-right"></i>
                            {{ sub_cat }}
                        </button>
                        <div class="dropdown-container">
                            {% for note_page in dropdowns[dropdown][sub_cat] %}
                                <div class="dropdown-link-container">
                                    <a class="notelink" href={{ dropdowns[dropdown][sub_cat][note_page] }}>{{ note_page }}</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <hr>
            <a href="{{ url_for('notes_bp.add_notes') }}">Add Notes</a>
            <a href="{{ url_for('notes_bp.manage_notes') }}">Manage Notes</a>
        {% endif %}
    </div>

</div>

<script>
    /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
    var dropdown = document.querySelectorAll(".dropdown-btn,.sub-dropdown-btn");
    var i;

    for (i = 0; i < dropdown.length; i++) {
        dropdown[i].addEventListener("click", function() {
            this.classList.toggle("active");
            sessionStorage.setItem(this.id, this.classList.value);
            console.log(sessionStorage)
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
        });
    }

    for (i = 0; i < dropdown.length; i++) {
        if (dropdown[i].id in sessionStorage) {
            dropdown[i].classList.value = sessionStorage.getItem(dropdown[i].id);
            if (dropdown[i].classList.contains('active')) {
                dropdown[i].nextElementSibling.style.display = "block";
            }
        }
    }

</script>